endpoints:
  first:
    provider: proxy1
    path: first
  second:
    provider:
      provider: postgres
      sql: select * from customers
  proxy1:
    provider: httpbin
    path: /get
    method: GET

  proxy2:
    provider: httpbin2
    path: /get

  users_get:
    provider: httpbin
    path: /users
    method:
      - GET
      - OPTION

  users_post:
    provider: httpbin
    path: /users
    method:
      - POST


providers:
  google-main-page:
    type: proxy
    path: google.com
    shema: https
    method: GET

  httpbin:
    type: proxy
    path: httpbin.org
    shema: https
    allowed:
      methods:
        - GET
        - POST
      parameters:
        - cat

  httpbin2:
    type: proxy
    path: httpbin.org
    allowed:
      methods:
        - GET
        - POST

  postgres:
    type: postgres
    user:
      root
    password:
      root
    db:
      some
    allowed:
      parameters: false
