endpoints:
  first:
    provider: httpbin
    path: /first

  first2:
    provider: httpbin
    path: /first2

  second:
    provider:
      ref: postgres
      sql: select * from users
    path: /customers
    method: GET

  third:
    provider:
      ref: postgres
      sql: select * from users
      is_single: false
    path: /customers2

providers:
  httpbin:
    type: proxy
    path: httpbin.org/get
    shema: https
    allowed:
      methods:
        - GET
        - POST
      parameters:
        - cat
        - param1

  postgres:
    type: postgres
    user:
      qwerty
    password:
      qwerty
    db:
      new
    port:
      10432
    allowed:
      parameters: false
