[package]
name = "apigen_contract"
version = "0.1.0"
authors = ["Sergey Murzin <sergey.murzin@dataart.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linked-hash-map = "0.5.2"
json="*"